---

- name: Get cdeployment-databases github project
  git:
    repo: "{{ deployment_databases_git }}"
    version: master
    dest: "{{ deployment_databases_git_path }}"
    force: yes

- name: Make my directory tree readable & executable
  file:
    path: "{{ deployment_databases_git_path }}/terraform"
    mode: 0777

- name: Copy Script for ssh config file
  copy:
    src:  ./files/sshConfig.sh
    dest: /home/{{ ansible_user }}/.ssh
    mode: 0777

