---

# Variable configuration.
- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Define postgresql_packages.
  set_fact:
    schedule_machine_packages: "{{ __schedule_machine_packages | list }}"
  when: schedule_machine_packages is not defined

- name: Define ppa ansible repo.
  set_fact:
    repo_ppa_ansible: "{{ __repo_ppa_ansible }}"
  when: repo_ppa_ansible is not defined

- name: Define terraform url binaries.
  set_fact:
    terraform_binaries_url: "{{ __terraform_binaries_url }}"
  when: terraform_binaries_url is not defined

- name: Define binaries path.
  set_fact:
    bin_path: "{{ __bin_path }}"
  when: bin_path is not defined

- name: Define terraform inventory url binaries.
  set_fact:
    terraform_inventory_binaries_url: "{{ __terraform_inventory_binaries_url }}"
  when: terraform_inventory_binaries_url is not defined