# Include Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  notify:
    - 'Restart airflow-scheduler'
    - 'Restart airflow-webserver'

- include_tasks: configure.yml
  notify: 'Restart airflow'

