---

# Handlers main file for airflow role

- name: 'Restart airflow'
  become: True
  service:
    name: "{{ item.name }}"
    state: 'restarted'
  with_items: "{{ airflow_services_states }}"
  when: "item.state == 'started'"

- name: 'Restart airflow-webserver'
  become: True
  service:
    name: "{{ item.name }}"
    state: 'restarted'
  with_items: "{{ airflow_services_states }}"
  when:
    - "item.name == 'airflow-webserver'"
    - "item.state == 'started'"

- name: 'Restart airflow-scheduler'
  become: True
  service:
    name: "{{ item.name }}"
    state: 'restarted'
  with_items: "{{ airflow_services_states }}"
  when:
    - "item.name == 'airflow-scheduler'"
    - "item.state == 'started'"

- name: 'Restart airflow-worker'
  become: True
  service:
    name: "{{ item.name }}"
    state: 'restarted'
  with_items: "{{ airflow_services_states }}"
  when:
    - "item.name == 'airflow-worker'"
    - "item.state == 'started'"

- name: 'Start airflowdb'
  become: True
  command: "airflow initdb"