---

# Airflow services management

- name: 'SERVICE | Manage environment file'
  template:
    src: "{{ role_path }}/templates/airflow.env.j2"
    dest: "{{ airflow_paths.files.environment.path }}"
    owner: "{{ airflow_paths.files.environment.owner | default('root') }}"
    group: "{{ airflow_paths.files.environment.group | default('root') }}"
    mode: "{{ airflow_paths.files.environment.mode | default('0644') }}"
  notify:
    - 'Restart airflow-webserver'
    - 'Restart airflow-scheduler'


- name: 'SERVICE | Manage services with upstart'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  notify: "{{ item.handler }}"
  with_items: "{{ airflow_services_upstart }}"
  when: "is_upstart_managed_system | bool"


- name: 'SERVICE | Manage systemd services'
  template:
    src: "{{ role_path }}/templates/systemd.service.j2"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  notify: "{{ item.handler }}"
  with_items: "{{ airflow_services_systemd }}"
  when: "is_systemd_managed_system | bool"


- name: 'SERVICE | Manage services with init.d'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  notify: "{{ item.handler }}"
  with_items: "{{ airflow_services_initd }}"
  when:
    - "not (is_upstart_managed_system | bool)"
    - "not (is_systemd_managed_system | bool)"


# Services states
- name: 'SERVICE | Manage airflow services states'
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled | default(False) }}"
    state: "{{ item.state }}"
  with_items: "{{ airflow_services_states }}"
