---

- hosts: airflow
  become: true
  tasks:
  - name: Install dependencies.
    become: yes
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop:
      - unzip
      - git
      - python-setuptools
      - jq
      - htop

  - name: Add ansible stable repository from PPA
    become: yes
    apt_repository: repo='ppa:ansible/ansible'

  - name: Install Ansible.
    become: yes
    apt: name=ansible state=present

  - name: Unarchive a file that needs to be downloaded terraform
    become: yes
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
      dest: /usr/bin
      remote_src: yes
      owner: root
      group: root

  - name: Unarchive a file that needs to be downloaded terraform
    become: yes
    unarchive:
      src: https://github.com/adammck/terraform-inventory/releases/download/v0.7-pre/terraform-inventory_v0.7-pre_linux_amd64.zip
      dest: /usr/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755

  - name: Create directory for gce creds
    file:
      path: /var/lib/gce
      state: directory
      mode: 0777

  - name: Copy ssh google_compute_engine to acces to instances
    copy:
      src:  ~/.ssh/google_compute_engine
      dest: /var/lib/gce
      mode: 0777

  - name: Allow write, read, excecute on rundeck
    file:
      path: /var/lib/gce/
      state: directory
      mode: 0777

  - name: Copy GCP credentials
    copy:
      src:  "~/Documents/gcp-keys/octo.json"
      dest: /var/lib/gce
      mode: 0777

  - name: Get cockroach-ansible-terraform project
    become: yes
    git:
      repo: https://github.com/caminale/deployment-databases.git
      version: master
      dest: /opt/deployment-databases
      accept_hostkey: yes
      force: yes

  - name: Make my directory tree readable
    file:
      path: /opt/deployment-databases/terraform
      mode: 0777

#  - name: Copy Script for ssh config file
#    copy:
#      src:  ./scripts/sshConfig.sh
#      dest: /home/{{ ansible_user }}/.ssh
#      mode: 0777
#
#  - name: Run the sshConfig to get the ip instances
#    become: yes
#    strategy: debug
#    command:  ~/.ssh/sshConfig.sh



...
